name       : gnome-weather
version    : '44.0'
release    : 26
source     :
    - https://download.gnome.org/sources/gnome-weather/44/gnome-weather-44.0.tar.xz : 6b0d38ac785041699df628926e35db7b5ffa086ee0d6934c222a19c6b9923baf
license    : GPL-2.0-only
component  : desktop.gnome
summary    : GNOME weather application
description: |
    Graphical application showing weather from around the whole world
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk4)
    - pkgconfig(gweather4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(libgeoclue-2.0)
rundeps    :
    - gjs
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
