name       : gnome-weather
version    : 3.26.0
release    : 14
source     :
    - https://download.gnome.org/sources/gnome-weather/3.26/gnome-weather-3.26.0.tar.xz : 965cc0d1b4d4e53c06d494db96f0b124d232af5c0e731ca900edd10f77a74c78
license    : GPL-2.0-only
component  : desktop.gnome
summary    : GNOME weather application
description: |
    Graphical application showing weather from around the whole world
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(libgeoclue-2.0)
rundeps    :
    - gjs
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
