name       : gnome-weather
version    : '41.0'
release    : 23
source     :
    - https://download.gnome.org/sources/gnome-weather/41/gnome-weather-41.0.tar.xz : e5614eb74297e072960d6447557fa9fbfccf24bfcb314944b6d976640ee62dee
license    : GPL-2.0-only
component  : desktop.gnome
summary    : GNOME weather application
description: |
    Graphical application showing weather from around the whole world
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(libgeoclue-2.0)
    - pkgconfig(libhandy-1)
rundeps    :
    - gjs
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
