name       : gnome-weather
version    : 3.36.1
release    : 22
source     :
    - https://download.gnome.org/sources/gnome-weather/3.36/gnome-weather-3.36.1.tar.xz : 68e6e646159f31c4525c3a5dd308fc0b88dcfc79b61351e9e930dd6efc2ce787
license    : GPL-2.0-only
component  : desktop.gnome
summary    : GNOME weather application
description: |
    Graphical application showing weather from around the whole world
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(libgeoclue-2.0)
rundeps    :
    - gjs
setup      : |
    %patch -p1 < $pkgfiles/Adapt-to-libgweather-API-changes.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
