name        : gnome-weather
version     : 3.16.2
release     : 6
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-weather/3.16/gnome-weather-3.16.2.tar.xz : 4ce5b5eb44eaee13ad6185ab6a01069a9030f894d9f97596be180091e42fbd91
license     : GPL-2.0+
summary     : GNOME weather application
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(gjs-1.0)
rundeps     :
    - gjs
description : |
    Graphical application showing weather from around the whole world
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
