name       : gnome-weather
version    : 3.32.1
release    : 15
source     :
    - https://download.gnome.org/sources/gnome-weather/3.32/gnome-weather-3.32.1.tar.xz : a4f0bac84c9106c4e99d4b5dacfcf6bc7daa94186711047894cb425446b50e76
license    : GPL-2.0-only
component  : desktop.gnome
summary    : GNOME weather application
description: |
    Graphical application showing weather from around the whole world
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(libgeoclue-2.0)
rundeps    :
    - gjs
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
