name       : gnome-weather
version    : 3.32.2
release    : 16
source     :
    - https://download.gnome.org/sources/gnome-weather/3.32/gnome-weather-3.32.2.tar.xz : 1a25c325033a134f291481bb4aa00b5c9af6555daf5bc311e963e629976bdd49
license    : GPL-2.0-only
component  : desktop.gnome
summary    : GNOME weather application
description: |
    Graphical application showing weather from around the whole world
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(libgeoclue-2.0)
rundeps    :
    - gjs
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
