name       : gnome-weather
version    : 3.24.0
release    : 11
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-weather/3.24/gnome-weather-3.24.0.tar.xz : e36847884670e59a71ac70ed982fc8f2fb70f1766c3a24f10a0cd38c9b66d574
license    : GPL-2.0
component  : desktop.gnome
summary    : GNOME weather application
description: |
    Graphical application showing weather from around the whole world
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(libgeoclue-2.0)
rundeps    :
    - gjs
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
