name       : gnome-weather
version    : 3.20.2
release    : 9
source     :
    - https://download.gnome.org/sources/gnome-weather/3.20/gnome-weather-3.20.2.tar.xz : 7823ca7c08fa852232b98c2517830e3bd9b0ab80c9ac83f182c18ec140a5c18b
license    : GPL-2.0
component  : desktop.gnome
summary    : GNOME weather application
description: |
    Graphical application showing weather from around the whole world
builddeps  :
    - pkgconfig(gjs-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(libgeoclue-2.0)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
