name       : gnome-weather
version    : 3.20.1
release    : 8
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-weather/3.20/gnome-weather-3.20.1.tar.xz : e310ecd56f396ac0e8e5652ac8b63258720034e23afbf32fbb2d509f25bbb2b6
license    : GPL-2.0+
summary    : GNOME weather application
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(libgeoclue-2.0)
    - pkgconfig(gjs-1.0)
rundeps    :
    - gjs
description: |
    Graphical application showing weather from around the whole world
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
