name        : gnome-weather
version     : 3.18.1
release     : 7
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-weather/3.18/gnome-weather-3.18.1.tar.xz : d0cbe0ee6e9f9332e30836d72c9a462ecc908a97402943c33cd6e61d08323fdf
license     : GPL-2.0+
summary     : GNOME weather application
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gweather-3.0)
    - pkgconfig(gjs-1.0)
rundeps     :
    - gjs
description : |
    Graphical application showing weather from around the whole world
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
